# Numpy

- Numpy is a fundamental package for scientific computing in python.
- It is a python library that provides multidimensional array objects and various derived objects such as Masked arrays or Matrices and a assortment of routines for fast operations on Arrays.
- It includes mathematical, Logical, Shape manipulation, sorting, selecting, I/O, Discrete Fourier Transform, Basic Linear Algebra, Stastical Operations, Random Simulations Etc.
- At the core of the Numpy Package is the dimensional Array object.

## Why Numpy ?

- Data types in python -> List and dictionary -> Slow
- We needed speed and less memory consumption to work on huge amount of data.
- Numpy was created in C language and wrapped in python.

- Libraries like Scikit Learn, Tensorflow, and Pytorch require input data in Numpy arrays or tensors

### Numpy Arrays Vs Python Sequences

- Numpy arrays have fixed size at creation, unlike python list, which grow dynamically.
- Changing the size of an ndim array will create a new array and delete the original
- The elements in a numpy array are required to be of the same data type and thus will be of the same size in memory
- Numpy arrays facilitate advanced mathematical and other types of operations on large number of data.
- Such Operations are executed more efficiantly with less code that is possible using python built in sequences.

In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [7]:
import numpy as np

In [12]:
sinlgeNPArray = np.array([1,2,3,4,5,6,7,8,9,10]) #vector or 1D array
print(sinlgeNPArray)
type(sinlgeNPArray)

[ 1  2  3  4  5  6  7  8  9 10]


numpy.ndarray

In [18]:
twoDArray = np.array([[1,2,3],[4,5,6],[7,8,9]]) #Metrics
print(twoDArray)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
threeDArray = np.array([[[1,2,3],[4,5,6]],[[1,2,5],[2,4,5]],[[5,6,8],[5,8,9]]])
print(threeDArray)

[[[1 2 3]
  [4 5 6]]

 [[1 2 5]
  [2 4 5]]

 [[5 6 8]
  [5 8 9]]]


#### dtype parameter - Which can help us out with deciding  the size of the data we are going to store in our array

In [21]:
np.array([1,2,3,5,6],dtype=np.int32) #int64, float, bool

array([1, 2, 3, 5, 6], dtype=int32)

#### arange(n) function
- It helps in providing the values over a certain range.
- arange(start,end-1,steps)

In [24]:
new_array = np.arange(1,25,2)
print(new_array)

[ 1  3  5  7  9 11 13 15 17 19 21 23]


#### Reshape function
- arrayobject.reshape(row,column)
- It helps us out in changing the shape of the array

In [26]:
n_array = np.arange(1,17)
print(n_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [27]:
n_array.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [28]:
n_array.reshape(2,8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [31]:
np.arange(1,20,2).reshape(2,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

#### ones(row,column)
- To make an array with value all as 1
- To initial the weight of neurons in neural network.

In [38]:
np.ones((5,4),dtype = np.int32)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

### zeros(row,coulums)
- To create an array with all value as 0

In [35]:
np.zeros((4,5),dtype=np.int32)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)

#### random(row,column)
- Create a array with random values from 0 to 1 inside our metrix

In [42]:
np.random.random((2,5))

array([[0.78954984, 0.40955036, 0.18990845, 0.14766222, 0.86747961],
       [0.66051077, 0.41667048, 0.88632763, 0.25251146, 0.09629624]])

#### identity(n)
- It helps in creating ther matric as an identity matrix
- It is sqaure matrix
- All diagonal values are 1 and others are 0

In [43]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### linspace()
- It makes sure that every value with the given range is going to have similar distance from each other.

In [46]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])