# Numpy

- Numpy is a fundamental package for scientific computing in python.
- It is a python library that provides multidimensional array objects and various derived objects such as Masked arrays or Matrices and a assortment of routines for fast operations on Arrays.
- It includes mathematical, Logical, Shape manipulation, sorting, selecting, I/O, Discrete Fourier Transform, Basic Linear Algebra, Stastical Operations, Random Simulations Etc.
- At the core of the Numpy Package is the dimensional Array object.

## Why Numpy ?

- Data types in python -> List and dictionary -> Slow
- We needed speed and less memory consumption to work on huge amount of data.
- Numpy was created in C language and wrapped in python.

- Libraries like Scikit Learn, Tensorflow, and Pytorch require input data in Numpy arrays or tensors

### Numpy Arrays Vs Python Sequences

- Numpy arrays have fixed size at creation, unlike python list, which grow dynamically.
- Changing the size of an ndim array will create a new array and delete the original
- The elements in a numpy array are required to be of the same data type and thus will be of the same size in memory
- Numpy arrays facilitate advanced mathematical and other types of operations on large number of data.
- Such Operations are executed more efficiantly with less code that is possible using python built in sequences.

In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [7]:
import numpy as np

In [12]:
sinlgeNPArray = np.array([1,2,3,4,5,6,7,8,9,10]) #vector or 1D array
print(sinlgeNPArray)
type(sinlgeNPArray)

[ 1  2  3  4  5  6  7  8  9 10]


numpy.ndarray

In [18]:
twoDArray = np.array([[1,2,3],[4,5,6],[7,8,9]]) #Metrics
print(twoDArray)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
threeDArray = np.array([[[1,2,3],[4,5,6]],[[1,2,5],[2,4,5]],[[5,6,8],[5,8,9]]])
print(threeDArray)

[[[1 2 3]
  [4 5 6]]

 [[1 2 5]
  [2 4 5]]

 [[5 6 8]
  [5 8 9]]]


#### dtype parameter - Which can help us out with deciding  the size of the data we are going to store in our array

In [21]:
np.array([1,2,3,5,6],dtype=np.int32) #int64, float, bool

array([1, 2, 3, 5, 6], dtype=int32)

#### arange(n) function
- It helps in providing the values over a certain range.
- arange(start,end-1,steps)

In [24]:
new_array = np.arange(1,25,2)
print(new_array)

[ 1  3  5  7  9 11 13 15 17 19 21 23]


#### Reshape function
- arrayobject.reshape(row,column)
- It helps us out in changing the shape of the array

In [26]:
n_array = np.arange(1,17)
print(n_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [27]:
n_array.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [28]:
n_array.reshape(2,8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [31]:
np.arange(1,20,2).reshape(2,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

#### ones(row,column)
- To make an array with value all as 1
- To initial the weight of neurons in neural network.

In [38]:
np.ones((5,4),dtype = np.int32)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

### zeros(row,coulums)
- To create an array with all value as 0

In [35]:
np.zeros((4,5),dtype=np.int32)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)

#### random(row,column)
- Create a array with random values from 0 to 1 inside our metrix

In [42]:
np.random.random((2,5))

array([[0.78954984, 0.40955036, 0.18990845, 0.14766222, 0.86747961],
       [0.66051077, 0.41667048, 0.88632763, 0.25251146, 0.09629624]])

#### identity(n)
- It helps in creating ther matric as an identity matrix
- It is sqaure matrix
- All diagonal values are 1 and others are 0

In [43]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### linspace()
- It makes sure that every value with the given range is going to have similar distance from each other.

In [46]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

### Attributes

- ndim : (N dimension) - To find the dimension of an numpy error

In [49]:
arr = np.array([1,2,3])
arr.ndim

1

In [68]:
arra = np.array([[[1,2,2],[3,4,5]],[[7,8,9],[5,6,8]]]).ndim
arra


3

- shape : It provides us with the rows and columns in our dataset or numpy error

In [84]:
threedarra = np.array([
    [[1,2],
     [3,4]],

    [[7,8],
     [5,6]],

    [[4,5],
    [5,8]]])
threedarra.shape
# print(arra)

3

- size : It tell the total numbers of elements present in the dataset or array.

In [85]:
sizearra = np.array([
    [[1,2],
     [3,4]],

    [[7,8],
     [5,6]],

    [[4,5],
    [5,8]]])

sizearra.size

12

- itemsize : to get the size of each element in the array or dataset

In [86]:

itemsizearra = np.array([
    [[1, 2],
     [3, 4]],

    [[7, 8],
     [5, 6]],

    [[4, 5],
     [5, 8]]],dtype=np.int32)

itemsizearra.itemsize

4

- dtype : Tell us the type of data stored in the array or dataset

In [90]:
itemsizearra = np.array([[1,2,4],
                        [1,4,5]])

itemsizearra.dtype

dtype('int64')



- astype() : It will be used to get the data type of the column in the dataset in the pandas and numpy as well for doing the data type changes of our overall array

In [91]:
newarray = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]])

In [95]:
new_array.astype("float64")

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19., 21., 23.])

## Mathematical Operations on NumPy

- Scalar Operations : A scalar value operation will be done with the overall array.

In [110]:
ar = np.random.random((3,4))*12
nar = ar.astype("int32")


### Scalar operation with matrix or array

### We can apply scalar operation with the array with arithmetic operations

In [111]:
np.round(nar + 5)

array([[13, 16,  5,  9],
       [13, 16, 11, 12],
       [16, 15,  8,  5]], dtype=int32)

In [112]:
np.round(nar - 5)

array([[ 3,  6, -5, -1],
       [ 3,  6,  1,  2],
       [ 6,  5, -2, -5]], dtype=int32)

In [113]:
np.round(nar / 2)

array([[4., 6., 0., 2.],
       [4., 6., 3., 4.],
       [6., 5., 2., 0.]])

### Relational operation on matrices and matrix

In [117]:
ar = np.random.random((3,4))*12
nar = ar.astype("int32")

In [120]:
nar > 5

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [119]:
nar < 6

array([[ True, False, False, False],
       [ True, False, False,  True],
       [ True,  True,  True, False]])

### Vector operations : Operations will be in between the given numbers of matrices

In [126]:
array_one = np.arange(1,10).reshape(3,3)
array_two = np.arange(11,20).reshape(3,3)

In [127]:
array_one + array_two

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [128]:
array_two - array_one

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [129]:
array_one * array_two

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

### Functions in Numpy for Machine Learning and Data Science

- max() : It is used to calculate max value inside a matrix or an array
    -   Syntax
        - np.max(array)

- min() : It is used to calculate min value inside a matrix or an array
    -   Syntax
        - np.min(array)

- axis : It Provides us idea about any operation value inside specific row or column, Or to get any specific value from row wise or column wise.
    - axis=0 -> Applying operation column wise
    - axis=1 -> Applying operation row wise

- sum() : It calculates sum of all elements in matrix
    - Syntax
        - np.sum(array)

- prod() : It return the product of all elements in array.
    - Syntax
        - np.prod(array)

In [131]:
arr = np.round(np.random.random((4,4))*50).astype("int32")
arr

array([[21, 47, 46, 38],
       [26, 10, 41, 22],
       [ 9,  8, 49, 29],
       [46, 17, 36, 14]], dtype=int32)

In [136]:
#to get the maximum value from the whole matrix
print(np.max(arr))
print(np.min(arr))

49
8


In [138]:
#Column wise max value using axis=0
print(np.max(arr,axis=0))
#Row wise max value using axis=1
print(np.max(arr,axis=1))

[46 47 49 38]
[47 41 49 46]


In [139]:
#Column wise min value using axis=0
print(np.min(arr,axis=0))
#Row wise min value using axis=1
print(np.min(arr,axis=1))

[ 9  8 36 14]
[21 10  8 14]


In [141]:
# printing sum of all values in array
print(np.sum(arr))

459


In [142]:
#Column wise sum value using axis=0
print(np.sum(arr,axis=0))
#Row wise sum value using axis=1
print(np.sum(arr,axis=1))

[102  82 172 103]
[152  99  95 113]


In [143]:
# printing product of all values in array
print(np.prod(arr))

8651224143546290176


In [144]:
#Column wise product value using axis=0
print(np.prod(arr,axis=0))
#Row wise product value using axis=1
print(np.prod(arr,axis=1))

[ 226044   63920 3326904  339416]
[1725276  234520  102312  394128]


## Statistical Functions in Numpy

- mean() : np.mean(array) -> Mean of all matrix inside a array or matrix

In [148]:
ar = np.arange(1,10)
ar

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [151]:
np.mean(ar)

np.float64(5.0)

In [164]:
arr = np.round(np.random.random((2,4))*50)
arr


array([[11., 13., 12., 17.],
       [ 9.,  5., 11., 13.]])

In [165]:
np.mean(arr,axis=0)

array([10. ,  9. , 11.5, 15. ])

In [166]:
np.mean(arr,axis=1)

array([13.25,  9.5 ])

- std() : np.std(array) -> It provides with the standard deviation of all values of the matrix or array.

In [167]:
np.std(arr,axis=1)

array([2.27760839, 2.95803989])

In [168]:
np.std(arr,axis=0)


array([1. , 4. , 0.5, 2. ])

- median() : np.median(array) -> To calculate Median of all values in the array or matrix

In [173]:
np.round(np.median(arr,axis=0)).astype("int32")

array([10,  9, 12, 15], dtype=int32)

In [170]:
np.std(arr,axis=1)

array([2.27760839, 2.95803989])

- var() : np.var(array) - > It calculates the variace of all the value sin the array or matrix.

In [174]:
np.var(arr)

np.float64(10.484375)

In [175]:
np.var(arr,axis=0)

array([ 1.  , 16.  ,  0.25,  4.  ])

## Trignometric function

- sin() : np.sin() -> Sin value for the value we are going to pass inside the function

In [180]:
np.sin(arr)

array([[-0.99999021,  0.42016704, -0.53657292, -0.96139749],
       [ 0.41211849, -0.95892427, -0.99999021,  0.42016704]])

- tan() : np.tan() -> Return the tan value of the passed argument

In [181]:
np.tan(arr)


array([[-225.95084645,    0.46302113,   -0.63585993,    3.49391565],
       [  -0.45231566,   -3.38051501, -225.95084645,    0.46302113]])

- tan() : np.tan() -> Return the tan value of the passed argument

In [182]:
np.tan(52)

np.float64(-6.053272382792838)

## DOT Product of matrices

- np.dot(matrix1,matrix2)
- Conditions : First Matrix Column = Second Matrix Row, First Matrix Row = Second Matrix Column
- And the result of the product matrix dimensions will be (First Matrix Row, Second matrix column)

In [199]:
arr_one = np.round(np.random.random((3,4))*50).astype("int32")
arr_two = np.round(np.random.random((4,3))*50).astype("int32")

In [200]:
arr_one


array([[40, 26, 20,  2],
       [ 6, 21, 17,  0],
       [15, 48,  2, 11]], dtype=int32)

In [202]:
arr_two

array([[42, 38,  7],
       [22, 49,  1],
       [25, 38,  2],
       [21, 31, 29]], dtype=int32)

In [204]:
resultDotProduct = np.dot(arr_one,arr_two)
resultDotProduct

array([[2794, 3616,  404],
       [1139, 1903,   97],
       [1967, 3339,  476]], dtype=int32)

- log() - > TO find the log of all values availabe in array or matrix

In [205]:
np.log(arr)

array([[2.39789527, 2.56494936, 2.48490665, 2.83321334],
       [2.19722458, 1.60943791, 2.39789527, 2.56494936]])

In [207]:
np.log(arr)

array([[2.39789527, 2.56494936, 2.48490665, 2.83321334],
       [2.19722458, 1.60943791, 2.39789527, 2.56494936]])

- exp() - > To calculate the exponential of all values inside the matrix

In [208]:
np.exp(arr)

array([[5.98741417e+04, 4.42413392e+05, 1.62754791e+05, 2.41549528e+07],
       [8.10308393e+03, 1.48413159e+02, 5.98741417e+04, 4.42413392e+05]])

- round() -> It helps with rounding off the float values to its nearest possible integer value , np.round(array)
- ciel() -> It will round of to next corresponding integer value, Ex 1.2 -> 2, 1.9-> 2
- floor() -> It will round of to previous corresponding integer value ,Ex 1.2 -> 1, 1.9 -> 1

In [216]:
ranAr = np.random.random((4,5))*100
ranAr

array([[55.86665197, 12.82691268, 49.17660801,  1.79012234, 58.05740736],
       [39.97473735, 86.32615091, 50.74176386, 94.70619617, 60.58703252],
       [47.99598045, 12.44359948, 76.71402659, 82.70356998, 50.27485625],
       [24.95208914, 33.90931171, 65.97851837, 36.87198182, 57.54987361]])

In [217]:
np.round(ranAr)

array([[56., 13., 49.,  2., 58.],
       [40., 86., 51., 95., 61.],
       [48., 12., 77., 83., 50.],
       [25., 34., 66., 37., 58.]])

In [218]:
np.ceil(ranAr)

array([[56., 13., 50.,  2., 59.],
       [40., 87., 51., 95., 61.],
       [48., 13., 77., 83., 51.],
       [25., 34., 66., 37., 58.]])

In [219]:
np.floor(ranAr)

array([[55., 12., 49.,  1., 58.],
       [39., 86., 50., 94., 60.],
       [47., 12., 76., 82., 50.],
       [24., 33., 65., 36., 57.]])

- transpose() ->